---
name: Save AWS CLI latest release version

# https://stackoverflow.com/questions/58465057/trigger-a-github-action-when-another-repository-creates-a-new-release

on:
  schedule:
    - cron: '17 10 * * *'

jobs:
  get-aws-cli-release-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with: ${{ secrets.REPO_SCOPED_TOKEN }}

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Fetch AWS CLI latest release version
        run: python get_latest_release.py
