---
name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Check out
        uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Setup Poetry
        run: pip install poetry

      - name: Install development virtualenv
        run: poetry install --no-interaction --verbose

      - name: Run Pre-Commit
        run: poetry run pre-commit run --all-files --verbose

      - name: Run PyTest
        run: poetry run pytest . --verbose
